{% set name = "clang-python" %}
{% set version = "6.0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/clang/clang-{{ version }}.tar.gz
  sha256: fea8d56f3f5f02f61c4c1160dbce0f4ff244b996993d35433124d4b505de8b79

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - clang

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs clang

about:
  home: https://pypi.org/project/clang/
  license: Apache v2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python Bindings for Clang'
  description: |
    These are unofficial Python bindings to clang as taken from the clang source tree, packaged for installation from PyPi.
    In the interest of keep things simple, this package will have the same version numbers as the clang release they were taken from. In the case of a mistake in packaging, a further patch versioning value will be added, such as 6.0.0.1.
  dev_url: https://github.com/ethanhs/clang

extra:
  recipe-maintainers:
    - sc0rpi0n101
